import type { Metadata } from "next";
import { Poppins, Cormorant_Garamond } from "next/font/google";
import "./globals.css";

const cormorantGaramond = Cormorant_Garamond({
  subsets:["latin"],
  variable: "--font-cormorant-garamond",
  weight: ["400"]
})
const poppins = Poppins({
  subsets:["latin"],
  variable: "--font-poppins",
  weight: ["400","600"]
})

export const metadata: Metadata = {
  title: "Data minig blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${cormorantGaramond.variable} ${poppins.variable} antialiased bg-neutral-100`}
      >
        {children}
      </body>
    </html>
  );
}
