import { ThemeProvider } from "@/components/theme-provider";
import LenisProvider from "@/providers/lenis-provider";
import type { Metadata } from "next";
import { Playfair_Display, Poppins } from "next/font/google";
import "./globals.css";
import TubeLightNavbar from "@/components/navbar";
import BackTopButton from "@/components/back-top-button";

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["400", "600"],
});

export const playfair = Playfair_Display({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-playfair",
  weight: ["400", "500", "600", "700"],
  style: ["normal", "italic"],
});

export const metadata: Metadata = {
  title: "Data minig blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${playfair.variable} ${poppins.variable} antialiased `}>
        <div className="min-h-dvh w-full relative bg-black overflow-y-scroll">
          <div
            className="inset-0 z-0 fixed"
            style={{
              background: `
                      radial-gradient(ellipse 120% 80% at 70% 20%, rgba(255, 20, 147, 0.15), transparent 50%),
                      radial-gradient(ellipse 100% 60% at 30% 10%, rgba(0, 255, 255, 0.12), transparent 60%),
                      radial-gradient(ellipse 90% 70% at 50% 0%, rgba(138, 43, 226, 0.18), transparent 65%),
                      radial-gradient(ellipse 110% 50% at 80% 30%, rgba(255, 215, 0, 0.08), transparent 40%),
                      #000000
                    `,
            }}
          />
          <main className="relative z-10">
            <ThemeProvider
              attribute="class"
              defaultTheme="dark"
              enableSystem
              disableTransitionOnChange
            >
              <TubeLightNavbar/>
              <LenisProvider>{children}</LenisProvider>
              <BackTopButton/>
            </ThemeProvider>
          </main>
        </div>
      </body>
    </html>
  );
}
